### ISSUE TITLE
Garbled prompt on opening new QTerminal window

### ISSUE THREAD

**Issue by pertplus** [lxde/qterminal#145]
Whenever I open QTerminal, instead of showing the full "[user@hotname ~]$ " prompt, I get a cut off version that looks like "ame `]$ stna" . This corrects itself if I press any key, or resize the window, but it would be nice to have the window open with a clean prompt.

**Comment by jleclanche** [comment]
What is your shell, shell version and your .rc file for that shell? Can you reproduce it in konsole?

**Comment by pmattern** [comment]
The problem seems to be associated with the font in use and its size.
I can reproduce using Courier or Free Mono at 10pt but not at e. g. 12pt as well as DejaVu Sans Mono at 6pt but neither at 10 or 15pt.
This also means that the problem isn't limited to a distinct font type like TTF.

Problem can't be reproduced in konsole 15.04.0 including all fonts / sizes stated above.

Nailing down an eventual influence of the shell as well as a commit causing the issue seems difficult.
Problem exists running bash 4.3.39 / QTermwidget da6838d / QTerminal 397259e as well as 4.3.033 / 109ee57 / 4adeb4d. Couldn't see it running the latter three on a production system 01/2015 but couldn't tell whether this is because they were compiled against older version of other system components or as I just didn't use the fonts in question then.
~/.bashrc all the time just the one placed in /etc/skel by the package plus some aliases.

While at it I stumbled upon two more problems regarding fonts:
Using Courier New from Microsoft Core Fonts at 10pt only half of the lines get displayed, run e. g. `ls -Al /etc`.
With DejaVu Sans Mono at 15 pt the preview in dialog window "Terminal Settings" gets cut.

All findings on up-to-date Arch Linux i686 or x86_64 using the distribution's packages.

**Comment by tsujan** [comment]
I confirm the existence of this issue and what @pmattern added.

When I use DejaVu Sans 9pt (my default font), the issue will only show up if I open QTerminal inside a folder with a long path string. As @pertplus told, it's corrected by pressing any key but, for me, NOT by resizing the window.

The strange thing is that when I open a new tab inside the same folder,  the path is shown correctly and the cursor is at the right position. So, the problem may be related to window creation.

**Comment by tsujan** [comment]
@pmattern 
Could you please test if the problem disappears in a new tab? It might be useful in narrowing down the possible causes.

**Comment by tsujan** [comment]
Apparently, I found (and fixed) the cause of the garbled text in my case but I still don't know if the fix works in all cases.

@pertplus and @pmattern
If you could just confirm that the text is OK when a new tab is opened in the same directory, a PR will be worth making.

**Comment by pmattern** [comment]
@tsujan 
I can confirm the problem ceases in new tabs.
E. g. make sure a suitable font is chosen and start QTerminal → problem exists in the single tab that's open. Open another Tab → problem doesn't exist therein but persists in the first tab of the window.
Btw. resizing the window does not restore the prompt here either, no matter which way it's done, but hitting some arbitrary key does.

**Comment by tsujan** [comment]
@pmattern 
Thank you! So, the issue is in window creation. Tomorrow I'll make a simple PR.

**Comment by tsujan** [comment]
@pmattern and @jleclanche 
So, #204 fixes the issue for you too?

**Comment by pmattern** [comment]
Unfortunately, all findings discussed so far can still be seen in lxde/qterminal@b4a4acf.

**Comment by tsujan** [comment]
> Unfortunately, all findings discussed so far can still be seen in lxde/qterminal@b4a4acf.

Even if you add `QCoreApplication::processEvents();` before that line? Strange! it's completely fixed here.

**Comment by pmattern** [comment]
> Even if you add QCoreApplication::processEvents(); before that line?

Not sure whether I got this right but I tested like this pmattern/qterminal@2acb1de as well in the meantime ([corresponding branch](https://github.com/pmattern/qterminal/commits/garbled-prompt)). Problem as described earlier still exists, much as in lxde/qterminal@b4a4acf.

Arch Linux, QTermWidget lxde/qtermwidget@10e1796, `~/.config/qterminal.org` removed before each test.

Don't remember exactly which OS you're running, it's some Debian flavour IIRC. Could the fact that lxde/qterminal@b4a4acf seems to fix the problem on your system but not here eventually be related to different versions of the various QTermWidget / QTerminal dependencies on those different platforms?

**Comment by tsujan** [comment]
> Not sure whether I got this right

You did.

I'm on Debian but compile all LXQT related apps from the source. I think I compiled QTermWidget a month ago, so I'll recompile its latest source soon. I'll also consider your point about dependencies.

In the meanwhile, would you please tell me exactly with which font and font size you can reproduce the problem? I tested all fonts I had with various sizes but couldn't reproduce it after the last commit.

**Comment by pmattern** [comment]
> In the meanwhile, would you please tell me exactly with which font and font size you can reproduce the problem?

As depicted in the first paragraph of https://github.com/lxde/qterminal/issues/145#issuecomment-111742996

**Comment by tsujan** [comment]
I tested with those fonts and font sizes and saw no garbled text:

![courier10](https://cloud.githubusercontent.com/assets/981076/12209338/7c878814-b667-11e5-9b90-ac4fd45275e2.png)
![djvu6](https://cloud.githubusercontent.com/assets/981076/12209341/7f2bd0f2-b667-11e5-8230-e63968ac570b.png)

On one occasion, the text was cut from above and below but once I restarted qterminal, it was OK. However, by "jumbled/garbled" I didn't mean that but a text missing some characters, as @pertplus described.

The word "garbled" is too general; @pmattern, could you show a screenshot of a jumbled/garbled text when you have time, please (I guess you're busy right now)?

**Comment by pmattern** [comment]
lxde/qterminal@b4a4acf, Courier 10pt, right after launching QTerminal
![qterminal_cropped-prompt_start](https://cloud.githubusercontent.com/assets/9860801/12209566/255e973e-b654-11e5-8905-ff6733a1faae.png)
and after hitting an arbitrary key
![qterminal_cropped-prompt_hit-key](https://cloud.githubusercontent.com/assets/9860801/12209570/2d998684-b654-11e5-8533-68cfcc53a9f7.png)

Arch Linux i686, same finding on x86_64.

**Comment by tsujan** [comment]
@pmattern 
in `~/.bashrc` I have:
````
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
````

Can I try yours?

**Comment by tsujan** [comment]
I guess yours should be something like
````
PS1='[\u@\h \w]\$ '
````
But still I couldn't make qterminal show a garbled prompt. For now, I'm at a loss.

**Comment by tsujan** [comment]
My latest thought: What #204 fixed was a different issue, which I encountered only with long directory paths. However, IMO, it isn't unrelated to the current issue and also to another problem that isn't reported yet. I think the problem is somewhere in `termwidgetholder.cpp` or `termwidget.cpp`.

**Comment by pmattern** [comment]
In the meantime I had a look at Debian testing in a KVM/QEMU VM as follows:
* QTermWidget and QTerminal either from the official repos or latest VCS code compiled from source
* `PS1=[...]` both the ones you stated which are the default ones provided by Debian and Arch Linux respectively (yes, the second one you were stating [above](https://github.com/lxde/qterminal/issues/145#issuecomment-170158543) is indeed the one I'm using normally on Arch Linux). Correct sourcing of `~/.bashrc` verified by some particular `alias`.
* Free Mono from package fonts-freefont-ttf
* `~/.config/qterminal.org/` removed before each series

That way the issue was reproducible 100%.

**Comment by tsujan** [comment]
I updated qtermwidget and the prompt was still OK with all fonts, font sizes and various PS1 settings. HOWEVER:

QTerminal has a deep painting problem. I could report a few bugs if it was of any help but I think all of them point to one and the same issue. Consider these two examples:

(1) Open qterminal in a folder whose path is so long that the prompt takes more than one line. Then maximize the terminal. The text isn't wrapped (#76) but the real problem shows up when you press any key.

(2) Do as above but this time, instead of maximizing, split the terminal vertically. Again, the text of the left half isn't wrapped but if you press any key on the left half and then pull the splitter to right, you'll see the real problem.

I hacked both qtermwidget and qterminal to work around the above problems and even to correct the text flow on resizing (#76) but the hacks were so *dirty* that they could have serious side effects.

IMO, some parts of qtermwidget and/or qterminal should be rewritten. I don't know which parts and how yet.

**Comment by tsujan** [comment]
Wow! After hours of studying and changing various parts of qtermwidget to no avail, I installed Konsole and saw exactly the same drawbacks in it. I was astonished why I hadn't noticed them under KDE.

So, qtermwidget has inherited its problems from Konsole. Because its code is simpler, I still have hope ;) `TerminalDisplay.cpp` seems to be responsible for updating the screen.

**Comment by agaida** [comment]
@tsujan - if one look through the issues, thats why we should remove the code borrowed from kde as soon as possible and use the now splitted up KF5 libs. They has improved the code since the time of forking and regarding some other issues pino suggest to go directly with upstream

The advantage will be, that we could make this behaviour an upstream issue and maybe provide patches upstream. So both projects would be better in the end.

**Comment by tsujan** [comment]
@agaida 
Konsole is already based on KF5 libs and independent from KDE. IMHO, the advantage of QTerminal+qtermwidget is that they're more manageable -- at least, theoretically -- exactly because they don't have KF5 dependency.
On the other hand, I prefer to have a working app instead of reporting bugs against KF5 ;) QTerminal is already a nice terminal emulator and it could be made better by us.

**Comment by tsujan** [comment]
At last, this is the cleanest hack I came up with:

https://github.com/tsujan/qtermwidget/commit/0517b83a8862742d3ed50bfca55b8c973726fa1d
https://github.com/tsujan/qterminal/commit/43c0da56b1535841f0ca8792263887363d308ab7

With just a few changes to qtermwidget and qterminal, it corrects the text flow on resizing (#76) and, hopefully, fixes the garbled text issue for all (@pmattern, only you could test the latter -- I couldn't reproduce it). No side effect that I know of.

A demo: https://dl.dropboxusercontent.com/u/7793460/vokoscreen-resizing.mkv

The problem of garbage text after widening a thin terminal with a long line still persists but it isn't specific to QTerminal or Konsole; XTerm, for example, has it too.

**Comment by agaida** [comment]
hmm, sorry, wasn't clear about what i want to archive, you are right with qtermial - i was thinking of: https://github.com/lxde/qtermwidget/issues/50 - and in that case a step back to the roots would help a lot.

**Comment by pmattern** [comment]
@tsujan 
Cannot see the problem any longer with tsujan/qtermwidget@18cafd4 / 
tsujan/qterminal@0a64380.

Btw. couldn't see it any longer either with tsujan/qtermwidget@18cafd4 plus your branch [text_flow_hack](https://github.com/tsujan/qterminal/commits/text_flow_hack) without tsujan/qterminal@b4a4acfaa79 (available in [this branch](https://github.com/pmattern/qterminal/commits/text_flow_hack_without-b4a4acf), FWIW).

**Comment by tsujan** [comment]
@pmattern
First thank you for taking time and testing them!

Yes, with this hack, https://github.com/tsujan/qterminal/commit/b4a4acfaa79 isn't needed but, aside from it being logical, it doesn't do any harm.

I didn't make any deep change, hence calling it a hack. Just a neutral key press is emulated to assure the correct text flow. I have a plan to go more deeply into qtermwidget's code in my free time.

Do you think they're worth 2 PR's? Or the garbled text is tolerable for now?

**Comment by pmattern** [comment]
If I got our discussion so far right tsujan/qterminal@0a64380 is just a workaround circumventing the so-called garbled prompt as displayed [here](https://github.com/lxde/qterminal/issues/145#issuecomment-170123903) by simulating some key press event and you are looking into some changes which will eventually fix the underlying problem as well as some more issues like failure to adjust to changed window sizes.

If so I do not see any need to push that workaround for now. The "garbled" prompt is only a minor usability issue anyway and can be avoided in an utterly trivial way (hit some arbitrary key).

**Comment by tsujan** [comment]
@pmattern OK :)

**Comment by tsujan** [comment]
Isn't the garbled prompt an issue anymore? I ask because, since then, I've always patched QTerminal and QTermWidget to have `QTermWidget::emulateKeyPress()`.

**Comment by agaida** [comment]
never see this issue on none of my installations on  no architecture (amd64, i386, armhf arch debian debian-kfree and Freebsd) in the last year
